name: "Terragrunt Validate and/or Plan"
author: "travis"
description: "Validate all terragrunt files within a project and optionally print out terragrunt deployment plans. This action can only be used for situations where AWS is the cloud provider and Kubernetes is the deployment target."
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/scripts/main.sh
      shell: bash
      working-directory: ${{ github.workspace }}/$WORKDIR
